;;; verify-config.el --- Isolated startup regression check -*- lexical-binding: t; -*-
;; Run: emacs -Q --batch -l tests/verify-config.el
;; Set EMACS_DOTS_TEST_PACKAGES to an existing Lambda var/elpa directory.
;; No packages are installed, refreshed or upgraded by this check.
(require 'cl-lib)
(require 'package)
(require 'package-vc)
(defvar dots-test-source
  (file-name-directory (directory-file-name (file-name-directory load-file-name))))
(defvar dots-test-root (make-temp-file "emacs-dots-check-" t))
(defvar dots-test-failures nil)
(defun dots-test-check (predicate description)
  (unless predicate (push description dots-test-failures)))
(defun dots-test-block-install (&rest args)
  (push (format "Unexpected package installation: %S" args) dots-test-failures)
  (error "Package installation disabled during verification"))
(dolist (fn '(package-install package-vc-install package-refresh-contents))
  (advice-add fn :override #'dots-test-block-install))
(dolist (file '("early-init.el" "init.el"))
  (copy-file (expand-file-name file dots-test-source)
             (expand-file-name file dots-test-root)))
(copy-directory (expand-file-name "lisp" dots-test-source)
                (expand-file-name "lisp" dots-test-root) nil t)
(dolist (directory '("literate" "tools"))
  (copy-directory (expand-file-name directory dots-test-source)
                  (expand-file-name directory dots-test-root) nil t))
(setq user-emacs-directory (file-name-as-directory dots-test-root)
      default-directory user-emacs-directory
      user-init-file (expand-file-name "init.el" user-emacs-directory)
      kittymacs-org-directory (expand-file-name "org/" user-emacs-directory)
      native-comp-jit-compilation nil)
(make-directory (expand-file-name "var/etc" user-emacs-directory) t)
(with-temp-file (expand-file-name "var/etc/custom.el" user-emacs-directory)
  (insert "(setq dots-test-custom-loaded t)\n"))
(with-temp-file (expand-file-name "lisp/private.el" user-emacs-directory)
  (insert "(unless (boundp 'kittymacs-project-directory) (error \"Private loaded before platform\"))\n"
          "(setq dots-test-private-loads (1+ (if (boundp 'dots-test-private-loads) dots-test-private-loads 0)))\n"
          "(setopt kittymacs-project-directory (expand-file-name \"test-projects/\" user-emacs-directory))\n"))
(when (getenv "EMACS_DOTS_TEST_PACKAGES")
  (advice-add 'package-initialize :before
              (lambda (&rest _)
                (setq package-user-dir (getenv "EMACS_DOTS_TEST_PACKAGES")))))
(condition-case err
    (progn
      (load (expand-file-name "early-init.el" user-emacs-directory) nil t)
      (load user-init-file nil t)
      (run-hooks 'after-init-hook)
      (run-hooks 'emacs-startup-hook)
      (require 'cus-edit)
      (dots-test-check (= dots-test-private-loads 1) "private.el must load once")
      (dots-test-check (equal kittymacs-project-directory
                              (expand-file-name "test-projects/" user-emacs-directory))
                       "Project override was overwritten")
      (dots-test-check (and (boundp 'dots-test-custom-loaded) dots-test-custom-loaded)
                       "Persistent Customize file was not loaded")
      (dots-test-check (string-suffix-p "var/etc/custom.el" custom-file)
                       "Customize file is not in persistent state")
      (dolist (feature '(kittymacs-literate kittymacs-dashboard kittymacs-meow
                        kittymacs-leader kittymacs-keys kittymacs-treesit kittymacs-languages
                        kittymacs-terminal kittymacs-treemacs kittymacs-org kittymacs-ui
                        kittymacs-frames))
        (dots-test-check (featurep feature) (format "Missing feature %s" feature)))
      (dots-test-check (equal custom-enabled-themes '(doom-sonokai)) "Theme changed")
      ;; Exercise the real loader in both directions: themes must not stack.
      (kittymacs-toggle-theme)
      (dots-test-check (equal custom-enabled-themes (list kittymacs-light-theme))
                       "Light theme toggle failed")
      (kittymacs-toggle-theme)
      (dots-test-check (equal custom-enabled-themes '(doom-sonokai))
                       "Sonokai was not restored by the theme toggle")
      (dots-test-check (and meow-global-mode doom-modeline-mode) "Editor modes missing")
      (dots-test-check (null kittymacs-eglot-auto-start-modes) "LSP auto-start changed")
      (dots-test-check (null kittymacs-language-packages) "Language package opt-ins changed")
      (dots-test-check (not (featurep 'kittymacs-key-hints)) "Hint adapter still loads")
      (dots-test-check (eq (lookup-key meow-normal-state-keymap (kbd "SPC")) kittymacs-leader-map)
                       "SPC is not the literal leader in Normal state")
      (dots-test-check (eq (lookup-key meow-motion-state-keymap (kbd "SPC")) kittymacs-leader-map)
                       "SPC is not the literal leader in Motion state")
      (dots-test-check (eq (lookup-key kittymacs-leader-map (kbd "l e")) #'kittymacs-eglot)
                       "SPC l is not the language-server menu")
      (dots-test-check (eq (lookup-key kittymacs-leader-map (kbd "s l")) #'vertico-repeat)
                       "SPC s l is not completion history")
      (dots-test-check (eq (lookup-key kittymacs-leader-map (kbd "h ?"))
                           #'kittymacs-dashboard-open-cheatsheet)
                       "Cheat-sheet leader binding was overwritten")
      (dots-test-check (eq (lookup-key kittymacs-leader-map (kbd "h h")) #'dashboard-open)
                       "Home leader binding was overwritten")
      (require 'bookmark) (require 'recentf) (require 'project)
      (save-window-excursion
        (let ((recentf-list (list user-init-file))
              (project--list nil) (bookmark-alist nil))
          (dashboard-open) (set-buffer dashboard-buffer-name)
          (run-hooks 'post-command-hook)
          (dots-test-check (eq (key-binding (kbd "?")) #'kittymacs-dashboard-open-cheatsheet)
                           "Dashboard shortcut is hidden by modal editing")
          (goto-char (point-min))
          (search-forward "Config")
          (widget-button-press (1- (point)))
          (dots-test-check (and (derived-mode-p 'org-mode)
                                (file-equal-p buffer-file-name
                                              (expand-file-name "literate/index.org" user-emacs-directory)))
                           "Dashboard Config did not open the literate guide")
          (dashboard-open) (set-buffer dashboard-buffer-name)
          (run-hooks 'post-command-hook)
          (goto-char (point-min))
          (search-forward "Keys & commands")
          ;; Activate the actual widget, including its callback arguments.
          (widget-button-press (1- (point)))
          (dots-test-check (and (derived-mode-p 'org-mode)
                                (file-equal-p buffer-file-name
                                              (expand-file-name "keybindings.org" kittymacs-lisp-dir)))
                           "Dashboard button did not open the cheat sheet")
          (goto-char (point-min))
          (while (re-search-forward "^| \\(SPC [^|]+?\\) +|[^|]+| \\([a-z][a-z0-9-]+\\) +|" nil t)
            (let* ((key (string-trim (match-string 1)))
                   (command (intern (match-string 2))))
              (dots-test-check (eq (lookup-key kittymacs-leader-map (kbd (substring key 4))) command)
                               (format "Cheat sheet binding mismatch: %s -> %s" key command)))))))
  (error (push (format "Startup error: %S" err) dots-test-failures)))
;; Check syntax without running installed packages' programming-mode hooks.
(let ((emacs-lisp-mode-hook nil) (prog-mode-hook nil))
  (dolist (file (append (list (expand-file-name "early-init.el" dots-test-source)
                             (expand-file-name "init.el" dots-test-source))
                        (directory-files (expand-file-name "lisp" dots-test-source)
                                         t "\\.el$")))
    (condition-case err
        (with-temp-buffer (insert-file-contents file) (emacs-lisp-mode) (check-parens))
      (error (push (format "Syntax %s: %S" file err) dots-test-failures)))))
(princ (format "\nEMACS-DOTS-VERIFY %s\nTemporary state: %s\nFailures: %S\n"
               (if dots-test-failures "FAIL" "PASS") dots-test-root dots-test-failures))
;; Avoid save-session hooks retaining any references to installed state on exit.
(setq kill-emacs-hook nil)
(kill-emacs (if dots-test-failures 1 0))
